name: Opened PRs

on:
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/dneimke/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
